### ISSUE TITLE
Stolen Api Key

### ISSUE THREAD

**Issue by peckpeck20** [deepakpandey01/Eye-Testing-Interface#1]
Hey!

I'm the owner of this API key, please remove ASAP.

You can generate your own for free using google maps

https://github.com/deepakpandey01/Eye-Testing-Interface/blob/9fdc79866d61474d5c4c43b0d26be52c5cbe5860/src/Screens/map.js#L56

**Comment by deepakpandey01** [comment]
Sorry, I was learning so did not created my own API key. But Removed.
